"use client"

import './globals.css'

export const metadata = {
  title: 'Carousel Demo',
  description: 'Created by Ogiboy - Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
